---
title: "mosaic_generation"
output: html_document
date: "2024-06-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(spatstat)
library(rayshader)
```

```{r}
X <- rpoislinetess(lambda = 5)
plot(as.im(X), main="rpoislinetess(5)")
plot(X, add=TRUE)
```
```{r}
Y <- as.im(X)
```

```{r}
X$n
```

```{r}
y <- as.matrix(as.integer(Y$v))
uniquefactors <- unique(y)
values <- rnorm(n = X$n, mean = 0, sd = 1)
dim(y) <- c(128,128)
```

```{r}
factor_to_value <- function(factoredimage, n, uniquefactors, factornumber)
{
  values <- rnorm(n = factornumber, mean = 0, sd = 1)
  df <- data.frame(factorindex = uniquefactors, factorvalues = values)
  image <- matrix(0, nrow = n, ncol = n)
  print(dim(factoredimage))
  for(i in 1:n)
  {
    for(j in 1:n)
    {
      current_index <- which(uniquefactors == factoredimage[i,j])[[1]]
      print(current_index)
      image[i,j] <- values[df$factorvalues[current_index]]
    }
  }
  return(image)
}
```


```{r}
factornumber <- length(uniquefactors)
image <- factor_to_value(y, 128, uniquefactors, factornumber)
plot(as.im(image), main="rpoislinetess(3)")
```



